// faqConfig.js
export const STOP_WORDS = new Set([
  "aku",
  "apa",
  "apakah",
  "atau",
  "bisa",
  "dan",
  "di",
  "ini",
  "itu",
  "jadi",
  "kak",
  "kalau",
  "ke",
  "nya",
  "produk",
  "saya",
  "yang",
  "gua",
  "gue",
  "gw",
  "sy",
  "aja",
  "dong",
  "nih",
  "deh",
  "lah",
  "udah",
  "sudah",
  "nihh",
  "dongg",
  "ya",
  "yaa",
  "oke",
  "ok",
  "yg",
  "buat",
  "untuk",
  "ada",
  "mau",
  "sih",
  "kok",
]);

export const OUT_OF_SCOPE_REPLY =
  "Maaf kak, kita hanya bisa jawab seputar pesanan kakak saja.";

export const GREETING_REPLY =
  "Halo kak, ada yang bisa dibantu seputar pesanan kakak?";

export const ORDER_KEYWORDS = [
  "alamat",
  "bayar",
  "cod",
  "harga",
  "kirim",
  "ongkir",
  "order",
  "paket",
  "payment",
  "pembayaran",
  "pesanan",
  "produk",
  "total",
  "transfer",
];

export const INTENT_GROUPS = [
  {
    name: "shipping",
    keywords: [
      "estimasi",
      "kapan sampai",
      "berapa lama",
      "lama sampai",
      "berapa hari",
      "pengiriman",
      "dikirim",
      "kirim",
      "sampai",
      "kurir",
      "resi",
      "tracking",
      "lacak",
      "cek paket",
      "paket dimana",
      "paket mana",
      "status paket",
      "belum sampai",
      "udah dikirim",
      "masih diproses",
      "udah jalan",
      "kapan dikirim",
      "barang kapan dikirim",
      "kapan berangkat",
      "sudah dikirim belum",
      "udah masuk ekspedisi",
      "paket saya mana",
      "barang saya mana",
      "kok belum nyampe",
      "belum nyampe",
      "belum datang",
      "sampai kapan",
      "pengiriman berapa hari",
      "estimasi berapa hari",
      "cek resi",
      "resi belum ada",
      "paket nyangkut",
    ],
    paths: [
      "shipping",
      "order.province",
      "order.addressClean",
      "order.ongkir",
      "order.state",
      "order.tracking",
    ],
  },

  {
    name: "pricing",
    keywords: [
      "harga",
      "berapa",
      "total",
      "ongkir",
      "bayar",
      "biaya",
      "cod",
      "diskon",
      "potongan",
      "promo",
      "cashback",
      "lebih murah",
      "voucher",
      "harga akhir",
      "total bayar",
      "semua jadi berapa",
      "berapa semua",
      "berapa totalnya",
      "bayarnya berapa",
      "harga fix",
      "ada promo",
      "promo gak",
      "diskon gak",
      "lebih hemat",
      "kena biaya lagi",
      "ada biaya tambahan",
      "bayar pas sampai",
    ],
    paths: ["pricing", "order.price", "order.productTitle"],
  },

  {
    name: "payment",
    keywords: [
      "payment",
      "pembayaran",
      "transfer",
      "cod",
      "bayar pakai",
      "metode pembayaran",
      "rekening",
      "bank",
      "qris",
      "belum bayar",
      "sudah bayar",
      "konfirmasi pembayaran",
      "dp",
      "lunas",
      "bayar dimana",
      "cara bayar",
      "transfer kemana",
      "bisa transfer",
      "bisa cod",
      "bayar nanti",
      "bayarnya gimana",
      "pembayaran aman",
      "bisa qris",
      "bisa ovo",
      "bisa dana",
      "bisa gopay",
    ],
    paths: ["order.paymentMethod", "pricing.cod"],
  },

  {
    name: "usage",
    keywords: [
      "cara",
      "pakai",
      "pasang",
      "install",
      "setting",
      "seting",
      "gunakan",
      "reset",
      "tutorial",
      "manual",
      "panduan",
      "cara pakai",
      "cara pasang",
      "cara install",
      "gimana pakainya",
      "cara setting",
      "cara konek",
      "cara hubungkan",
      "cara aktifkan",
      "cara nyalain",
      "tidak bisa dipakai",
      "cara reset",
      "petunjuk",
    ],
    paths: ["usage", "specification.app", "constraints"],
  },

  {
    name: "package",
    keywords: [
      "isi",
      "paket",
      "dapat apa",
      "kelengkapan",
      "box",
      "isi box",
      "isi dus",
      "dapat bonus",
    ],
    paths: ["specification.package_content", "package_content", "identity"],
  },

  {
    name: "feature",
    keywords: [
      "fitur",
      "fungsi",
      "support",
      "mendukung",
      "spesifikasi",
      "spek",
      "bisa",
      "compatible",
      "kompatibel",
      "fiturnya",
      "support android",
      "support iphone",
      "cocok buat",
      "bisa dipakai",
      "bisa connect",
      "support ios",
      "support samsung",
      "support xiaomi",
      "ada fitur",
      "apa aja fiturnya",
      "support bluetooth",
      "support wifi",
      "support hotspot",
      "support aplikasi",
      "fitur lengkap",
    ],
    paths: ["features", "specification", "constraints"],
  },

  {
    name: "order_summary",
    keywords: [
      "status",
      "sudah diproses",
      "dipacking",
      "diproses",
      "pending",
      "menunggu",
      "sedang dikirim",
      "udah dipacking",
      "udah proses",
      "udah jalan",
      "status sekarang",
      "status order",
      "order saya gimana",
      "pesanan saya dimana",
      "sudah masuk",
      "masih pending",
      "belum diproses",
      "udah dikemas",
    ],
    paths: [
      "order.productTitle",
      "order.price",
      "order.ongkir",
      "order.paymentMethod",
      "order.quantity",
    ],
  },

  {
    name: "address_change",
    keywords: [
      "ubah alamat",
      "ganti alamat",
      "alamat salah",
      "alamat baru",
      "edit alamat",
    ],
    paths: ["order.addressClean", "policy.address_change"],
  },

  {
    name: "cancel_order",
    keywords: [
      "batalkan",
      "cancel",
      "gak jadi",
      "tidak jadi",
      "batal pesanan",
      "stop order",
    ],
    paths: ["policy.cancellation", "order.state"],
  },

  {
    name: "stock",
    keywords: [
      "stok",
      "ready",
      "tersedia",
      "masih ada",
      "habis",
      "warna tersedia",
      "varian",
    ],
    paths: ["inventory", "product.stock"],
  },

  {
    name: "complaint",
    keywords: [
      "kecewa",
      "komplain",
      "buruk",
      "lama",
      "tidak sesuai",
      "beda",
      "marah",
      "tolong",
      "gimana ini",
      "kok begini",
      "parah",
      "jelek",
      "salah kirim",
      "barang salah",
      "barang kurang",
      "ga sesuai",
      "tidak cocok",
      "kecewa banget",
      "lama banget",
      "tolong bantu",
    ],
    paths: ["policy", "support", "warranty"],
  },

  {
    name: "greeting",
    keywords: [
      "halo",
      "hai",
      "hi",
      "hello",
      "pagi",
      "siang",
      "sore",
      "malam",
      "permisi",
      "assalamualaikum",
      "test",
      "tes",
      "halo admin",
      "admin",
      "kak",
      "min",
      "halo kak",
      "izin tanya",
    ],
    paths: [],
  },
];

export const CLOSING_KEYWORDS = [
  "oke makasih",
  "ok makasih",
  "oke terima kasih",
  "ok terima kasih",
  "siap makasih",
  "siap terima kasih",
  "thanks",
  "thank you",
  "noted",
  "oke kak",
  "siap kak",
  "paham",
  "udah paham",
  "sudah paham",
  "cukup",
  "sudah cukup",
  "gapapa",
  "gak papa",
  "tidak ada lagi",
  "ga ada lagi",
  "aman",
  "mantap",
];

export const CLOSING_REPLY_WITH_ESTIMATION = (estimation) =>
  `Siap kak, mohon ditunggu ya, paket kakak akan segera sampai dalam estimasi ${estimation} 🙏`;

export const CLOSING_REPLY_DEFAULT =
  "Siap kak, mohon ditunggu ya, paket kakak akan segera sampai 🙏";
